### ISSUE TITLE
🐞 Bug – Unable to start the development server

### ISSUE THREAD

**Issue by jamesrweb** [elm-land/elm-land#40] opened 2022-09-15 17:44 UTC
## Problem

Running the `elm-land server` command results in an `EPERM` error code being thrown.

## Your setup

OS: MacOS Monterey 12.5
Node: tested with v17.0.1 and v18.9.0
Elm land: v0.17.1

# Notes

The exact error looks like so:

```txt
[Error: EPERM: operation not permitted, scandir '/Users/<user>/.Trash'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/<user>/.Trash'
}
```

**Comment by marciofrayze** [comment] 2022-09-16 00:43
I'm having the same issues. It works fine if I run it on /tmp though.

 MacOS 12.6.
 Node v14.19.2.
 Elm-land v0.17.1.

The cli test suite also fails in the same points (and passes if I run it from /tmp/elm-land/cli).

I also get an error if I try to list my .Trash folder. I guess it's related:
```
 ~  cd ~/.Trash
 ~/.Trash  ls
ls: .: Operation not permitted
```
For some reason, my ~/.Trash folder's permissions are:
```
drwx------    18 <myuser>  staff   576B 14 Set 18:01 .Trash
```
Even sudo is not allowed to look inside it!
```
 ~  sudo ls .Trash 
ls: .Trash: Operation not permitted
```

BUT, I can create and remove files in it:
```
 ~/.Trash  touch a                                                                                                                                                                      1 err
 ~/.Trash  rm -f a
```

And I don't know why elm-land is trying to peek into this folder.

I'm pretty sure giving full access to the terminal would fix this. But that's something that I would like to avoid doing (and guess shouldn't be necessary). More about it here: https://apple.stackexchange.com/questions/376916/cannot-ls-trash-in-the-terminal-in-catalina-operation-not-permitted#376917

**Comment by ryannhg** [comment] 2022-09-25 22:41
Thank you for reporting this!

I'm not sure why this is happening, it's likely related to how the underlying Vite server is trying to create folders for you automatically.

If we can't fix the root of the issue, at the very least, I'd like to have a friendlier error message to let folks know how to get unstuck!

---

@marciofrayze and @jamesrweb I have two questions for you that might help folks encountering these problems:

1. Does changing your terminal's permissions actually fix the issue on your machines?

2. Do you see the same error when running Elm Land commands within your editor's integrated terminal?

**Comment by jamesrweb** [comment] 2022-09-25 22:59
> Thank you for reporting this!
> 
> 
> 
> I'm not sure why this is happening, it's likely related to how the underlying Vite server is trying to create folders for you automatically.
> 
> 
> 
> If we can't fix the root of the issue, at the very least, I'd like to have a friendlier error message to let folks know how to get unstuck!
> 
> 
> 
> ---
> 
> 
> 
> @marciofrayze and @jamesrweb I have two questions for you that might help folks encountering these problems:
> 
> 
> 
> 1. Does changing your terminal's permissions actually fix the issue on your machines?
> 
> 
> 
> 2. Do you see the same error when running Elm Land commands within your editor's integrated terminal?

1. No. Changing permissions on the folder / file or terminal does nothing to change the error. It's simply protected AFAICS.

2. Yes.

**Comment by jamesrweb** [comment] 2022-09-25 23:16
@ryannhg I wonder if it's got something to do with looking for / scanning for the elm land json in the user folder tree as I see in the build command for example. WDYT?

**Comment by marciofrayze** [comment] 2022-09-26 14:55
Running inside VSCode's terminal (tested with zsh and bash) I get the same error.

When giving full disk access permission to iTerm 2, I got a weird result: now `elm-land server` just halts. No error messages.

Still runs fine on /tmp.

![Captura de Tela 2022-09-26 às 11 52 36](https://user-images.githubusercontent.com/40629/192309558-d6a7ccf6-efc4-4040-8012-36d06ca79dde.png)


(The screenshot is in portuguese, sorry about that, but "Acesso Total ao Disco" means "Full Disk Access")

**Comment by marciofrayze** [comment] 2022-10-14 20:06
Some more information about this. If I checkout this repo and create the project inside of it, it works! No idea why.
Here is the output of 2 tests, one created inside the repo and one outside:

```
 ~/dev/github/elm-land/projects/cli  on main !1 ?4  elm-land init test1                                                                                                                    ok

🌈  Elm Land (v0.17.2) created a new project in ./test1
    ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
    Here are some next steps:

    📂 cd test1
    🚀 elm-land server

 ~/dev/github/elm-land/projects/cli  on main !1 ?5  cd test1                                                                                                                               ok
 ~/dev/github/elm-land/projects/cli/test1  on main !1 ?5  elm-land server                                                                                                                  ok

🌈  Elm Land (v0.17.2) is ready at http://localhost:1235
    ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
^C
 ~/dev/github/elm-land/projects/cli/test1  on main !1 ?5  cd ..                                                                                                                           INT
 ~/dev/github/elm-land/projects/cli  on main !1 ?5  cd ..                                                                                                                                  ok
 ~/dev/github/elm-land/projects  on main !1 ?5  elm-land init test2                                                                                                                        ok

🌈  Elm Land (v0.17.2) created a new project in ./test2
    ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
    Here are some next steps:

    📂 cd test2
    🚀 elm-land server

 ~/dev/github/elm-land/projects  on main !1 ?6  cd test2/                                                                                                                                  ok
 ~/dev/github/elm-land/projects/test2  on main !1 ?6  elm-land server                                                                                                                      ok
[Error: EPERM: operation not permitted, scandir '/Users/mfdavid/.Trash'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/mfdavid/.Trash'
}

❗️ Had trouble starting the server...
```

**Comment by marciofrayze** [comment] 2022-10-14 20:24
It gets weirder. If I delete the package.json file from the folder above, it stops working again:

```
~/dev/github/elm-land/projects/cli ls                                                                                                                                        
README.md         node_modules      package           package-lock.json package.json      src               test1             tests
 ~/dev/github/elm-land/projects/cli cd test1                                                                                                                               
 ~/dev/github/elm-land/projects/cli/test1 elm-land server                                                                                                                  

🌈  Elm Land (v0.17.2) is ready at http://localhost:1235
    ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
^C
 ~/dev/github/elm-land/projects/cli/test1 cd ..                                                                                                                           
 ~/dev/github/elm-land/projects/cli rm package.json                                                                                                                        
 ~/dev/github/elm-land/projects/cli ls                                                                                                                                     
README.md    node_modules package      src          test1        tests
 ~/dev/github/elm-land/projects/cli cd test1                                                                                                                               
 ~/dev/github/elm-land/projects/cli/test1 elm-land server                                                                                                                  
[Error: EPERM: operation not permitted, scandir '/Users/mfdavid/.Trash'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/mfdavid/.Trash'
}

❗️ Had trouble starting the server...
```

**Comment by marciofrayze** [comment] 2022-10-24 16:27
Yet another update: I got a new computer (a MacBook Air with M2 chip) and the problem is gone.

**Comment by junebugfix** [comment] 2023-03-03 20:45
I'm on macOS 12.6 - I was experiencing this error but giving Full Disk Access to Terminal fixed it!

**Comment by ryannhg** [comment] 2023-04-22 20:45
Going to close this issue for now, but will see if it pops up again later! 🕵️

**Closed by ryannhg** 2023-04-22 20:45 UTC
Labels: bug, @elm-land/app

**Comment by itouuuuuuuuu** [comment] 2023-04-28 08:58
Try running the `npm init` command.

**Comment by frontmesh** [comment] 2023-05-04 10:42
This issue is still happening and what @itouuuuuuuuu mentioned solved the issue.
